require('plugins.comment')
require('plugins.lualine')
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.toggleterm')
require('plugins.lsp')
require('plugins.impatient')
